language: elixir
otp_release:
  - 17.4
install:
  - mix local.hex --force
  - mix local.rebar --force
  - mix deps.get --only test
script:
  - mix test
after_script:
  - MIX_ENV=docs mix deps.get
  - MIX_ENV=docs mix inch.report
